### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by rbw** [ITRS-Group/check_aws#4]
- [ ] Implement Ratio model
- [x] Add support for *Units* (obtain CLI enum using boto)
- [x] Rename project (as it's not specific to EC2), perhaps to *check_aws*
- [ ] Add Docstrings
- [ ] Tests
  - [ ] More ec2cw.Resource tests
- [ ] Examples
  - [ ] Add example using Ratio
  - [x] Fix issues with AWS/VPN example
  - [x] Add more EC2 examples
- [ ] Monitor integration
  - [x] Management Packs: ITRS-Group/monitor-management-packs
  - [x] Metadata: ITRS-Group/system-addons-plugins-metadata
  - [x] Check commands: ITRS-Group/monitor-config
  - [x] Available via repos: ITRS-Group/system-addons-plugins-op5-plugins-op5
  - [ ] Docs, Zendesk
